In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/ecommerce_dataset.csv")

In [3]:
df.head(10)

,order_id,customer_id,order_date,product,category,quantity,unit_price,discount_percent,total_amount,city,payment_method,order_status
0,462,1085,2025-01-01,Running Shoes,Beauty,1,222.94,20,178.35,Port Harcourt,Bank Transfer,Delivered
1,83,1193,2025-01-01,Laptop Stand,Sports,1,61.44,5,58.37,Ibadan,Card,Delivered
2,760,1174,2025-01-01,Bluetooth Speaker,Clothing,4,498.37,10,1794.13,Lagos,Bank Transfer,Delivered
3,297,1112,2025-01-02,Smart Watch,Home & Kitchen,5,19.33,5,91.82,Kano,Wallet,Cancelled
4,170,1169,2025-01-02,Yoga Mat,Beauty,1,209.89,15,178.41,Ibadan,Cash on Delivery,Delivered
5,719,1101,2025-01-03,Smart Watch,Clothing,2,341.56,15,580.65,Kano,Cash on Delivery,Delivered
6,844,1050,2025-01-03,Coffee Maker,Beauty,1,286.55,5,272.22,Lagos,Card,Delivered
7,603,1079,2025-01-04,Running Shoes,Home & Kitchen,4,400.78,0,1603.12,Abuja,Card,Processing
8,438,1237,2025-01-05,Laptop Stand,Beauty,5,69.12,15,293.76,Port Harcourt,Cash on Delivery,Delivered
9,916,1026,2025-01-05,Bluetooth Speaker,Beauty,3,399.94,0,1199.82,Ibadan,Card,Delivered

In [4]:
df.head()

,order_id,customer_id,order_date,product,category,quantity,unit_price,discount_percent,total_amount,city,payment_method,order_status
0,462,1085,2025-01-01,Running Shoes,Beauty,1,222.94,20,178.35,Port Harcourt,Bank Transfer,Delivered
1,83,1193,2025-01-01,Laptop Stand,Sports,1,61.44,5,58.37,Ibadan,Card,Delivered
2,760,1174,2025-01-01,Bluetooth Speaker,Clothing,4,498.37,10,1794.13,Lagos,Bank Transfer,Delivered
3,297,1112,2025-01-02,Smart Watch,Home & Kitchen,5,19.33,5,91.82,Kano,Wallet,Cancelled
4,170,1169,2025-01-02,Yoga Mat,Beauty,1,209.89,15,178.41,Ibadan,Cash on Delivery,Delivered

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1000 non-null   int64
 1   customer_id       1000 non-null   int64
 2   order_date        1000 non-null   object
 3   product           1000 non-null   object
 4   category          1000 non-null   object
 5   quantity          1000 non-null   int64
 6   unit_price        1000 non-null   float64
 7   discount_percent  1000 non-null   int64
 8   total_amount      1000 non-null   float64
 9   city              1000 non-null   object
 10  payment_method    1000 non-null   object
 11  order_status      1000 non-null   object
dtypes: float64(2), int64(4), object(6)
memory usage: 93.9+ KB

In [7]:
df.isnull().sum()

order_id            0
customer_id         0
order_date          0
product             0
category            0
quantity            0
unit_price          0
discount_percent    0
total_amount        0
city                0
payment_method      0
order_status        0
dtype: int64