In [5]:
import sqlite3
import pandas as pd

# Connect to a SQLite database file
conn = sqlite3.connect("ecommerce.db")

In [6]:
import os
print(os.getcwd())  # shows current working directory

c:\Users\ADEGOKE\Desktop\DS-ML-AI\2026-Project-Building-Class-Journey-For-Beginners

In [7]:
# Load CSV into pandas
df = pd.read_csv("data/ecommerce_dataset.csv")

In [8]:
# Save it as a SQL table
df.to_sql("orders", conn, if_exists="replace", index=False)
print(f"✅ Done! Loaded {len(df):,} rows into SQLite")
print(f"Tables in SQLite {df.columns.to_list()}")

✅ Done! Loaded 1,000 rows into SQLite
Tables in SQLite ['order_id', 'customer_id', 'order_date', 'product', 'category', 'quantity', 'unit_price', 'discount_percent', 'total_amount', 'city', 'payment_method', 'order_status']

In [9]:
# Create a Helper Function

def run_sql(query):
    return pd.read_sql(query, conn)

In [10]:
run_sql("SELECT * FROM orders;")

,order_id,customer_id,order_date,product,category,quantity,unit_price,discount_percent,total_amount,city,payment_method,order_status
0,462,1085,2025-01-01,Running Shoes,Beauty,1,222.94,20,178.35,Port Harcourt,Bank Transfer,Delivered
1,83,1193,2025-01-01,Laptop Stand,Sports,1,61.44,5,58.37,Ibadan,Card,Delivered
2,760,1174,2025-01-01,Bluetooth Speaker,Clothing,4,498.37,10,1794.13,Lagos,Bank Transfer,Delivered
3,297,1112,2025-01-02,Smart Watch,Home & Kitchen,5,19.33,5,91.82,Kano,Wallet,Cancelled
4,170,1169,2025-01-02,Yoga Mat,Beauty,1,209.89,15,178.41,Ibadan,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
995,140,1127,2025-12-30,Running Shoes,Home & Kitchen,3,434.07,10,1171.99,Lagos,Cash on Delivery,Processing
996,808,1224,2025-12-30,Bluetooth Speaker,Books,1,337.78,0,337.78,Abuja,Wallet,Processing
997,39,1077,2025-12-30,Running Shoes,Sports,2,91.29,5,173.45,Abuja,Wallet,Processing
998,602,1238,2025-12-31,Bluetooth Speaker,Electronics,4,174.70,15,593.98,Ibadan,Bank Transfer,Delivered
999,842,1031,2025-12-31,Face Moisturizer,Home & Kitchen,4,407.37,10,1466.53,Abuja,Bank Transfer,Delivered

In [11]:
run_sql("SELECT city FROM orders;")

              city
0    Port Harcourt
1           Ibadan
2            Lagos
3             Kano
4           Ibadan
..             ...
995          Lagos
996          Abuja
997          Abuja
998         Ibadan
999          Abuja

[1000 rows x 1 columns]

In [12]:
run_sql("SELECT order_id FROM orders;")

     order_id
0         462
1          83
2         760
3         297
4         170
..        ...
995       140
996       808
997        39
998       602
999       842

[1000 rows x 1 columns]

In [13]:
run_sql("SELECT payment_method FROM orders;")

       payment_method
0       Bank Transfer
1                Card
2       Bank Transfer
3              Wallet
4    Cash on Delivery
..                ...
995  Cash on Delivery
996            Wallet
997            Wallet
998     Bank Transfer
999     Bank Transfer

[1000 rows x 1 columns]

In [14]:
run_sql("SELECT * FROM orders LIMIT 5;")

,order_id,customer_id,order_date,product,category,quantity,unit_price,discount_percent,total_amount,city,payment_method,order_status
0,462,1085,2025-01-01,Running Shoes,Beauty,1,222.94,20,178.35,Port Harcourt,Bank Transfer,Delivered
1,83,1193,2025-01-01,Laptop Stand,Sports,1,61.44,5,58.37,Ibadan,Card,Delivered
2,760,1174,2025-01-01,Bluetooth Speaker,Clothing,4,498.37,10,1794.13,Lagos,Bank Transfer,Delivered
3,297,1112,2025-01-02,Smart Watch,Home & Kitchen,5,19.33,5,91.82,Kano,Wallet,Cancelled
4,170,1169,2025-01-02,Yoga Mat,Beauty,1,209.89,15,178.41,Ibadan,Cash on Delivery,Delivered

In [15]:
run_sql("PRAGMA table_info(orders);")

    cid              name     type  notnull dflt_value  pk
0     0          order_id  INTEGER        0       None   0
1     1       customer_id  INTEGER        0       None   0
2     2        order_date     TEXT        0       None   0
3     3           product     TEXT        0       None   0
4     4          category     TEXT        0       None   0
5     5          quantity  INTEGER        0       None   0
6     6        unit_price     REAL        0       None   0
7     7  discount_percent  INTEGER        0       None   0
8     8      total_amount     REAL        0       None   0
9     9              city     TEXT        0       None   0
10   10    payment_method     TEXT        0       None   0
11   11      order_status     TEXT        0       None   0

In [16]:
run_sql("""
    SELECT category, city, product, total_amount
    FROM orders
    WHERE city = 'Lagos'
    ORDER BY total_amount DESC
    LIMIT 20;
"""
)

          category   city                  product  total_amount
0           Sports  Lagos      Wireless Headphones       2398.85
1   Home & Kitchen  Lagos              Smart Watch       2377.65
2           Sports  Lagos            Running Shoes       2285.50
3            Books  Lagos            Running Shoes       2263.15
4           Beauty  Lagos        Bluetooth Speaker       2125.17
5           Beauty  Lagos  Python Programming Book       2115.56
6            Books  Lagos           Cotton T-Shirt       2070.99
7      Electronics  Lagos      Wireless Headphones       2049.82
8   Home & Kitchen  Lagos                 Yoga Mat       1964.32
9   Home & Kitchen  Lagos             Coffee Maker       1943.14
10          Sports  Lagos             Coffee Maker       1935.62
11        Clothing  Lagos  Python Programming Book       1922.18
12           Books  Lagos                 Yoga Mat       1901.61
13  Home & Kitchen  Lagos            Running Shoes       1851.35
14        Clothing  Lagos        Bluetooth Speaker       1794.13
15     Electronics  Lagos           Cotton T-Shirt       1781.49
16          Sports  Lagos      Wireless Headphones       1717.09
17          Sports  Lagos              Smart Watch       1710.20
18          Sports  Lagos           Cotton T-Shirt       1709.80
19          Sports  Lagos             Laptop Stand       1668.04

In [17]:
run_sql("""
    SELECT order_status, quantity, city, product
    FROM orders
    WHERE city = 'Ibadan'
    ORDER BY quantity DESC
    LIMIT 20;
""")

   order_status  quantity    city                  product
0     Delivered         5  Ibadan            Running Shoes
1       Shipped         5  Ibadan              Smart Watch
2     Delivered         5  Ibadan      Wireless Headphones
3     Delivered         5  Ibadan             Laptop Stand
4     Cancelled         5  Ibadan         Face Moisturizer
5     Delivered         5  Ibadan                 Yoga Mat
6     Delivered         5  Ibadan             Laptop Stand
7     Delivered         5  Ibadan  Python Programming Book
8     Delivered         5  Ibadan  Python Programming Book
9     Delivered         5  Ibadan             Laptop Stand
10    Delivered         5  Ibadan            Running Shoes
11    Delivered         5  Ibadan        Bluetooth Speaker
12      Shipped         5  Ibadan         Face Moisturizer
13      Shipped         5  Ibadan  Python Programming Book
14    Delivered         5  Ibadan           Cotton T-Shirt
15    Delivered         5  Ibadan              Smart Watch
16   Processing         5  Ibadan         Face Moisturizer
17    Delivered         5  Ibadan  Python Programming Book
18    Delivered         5  Ibadan         Face Moisturizer
19    Delivered         5  Ibadan        Bluetooth Speaker

In [18]:
run_sql("""
    SELECT order_id, customer_id, order_date, quantity, category, unit_price, payment_method 
    FROM orders
    WHERE payment_method = 'Bank Transfer'
    ORDER BY order_date DESC
    LIMIT 30
""")
# order_id	customer_id	order_date	product	category	
# quantity	unit_price	discount_percent	
# total_amount	city	payment_method	order_status

,order_id,customer_id,order_date,quantity,category,unit_price,payment_method
0,602,1238,2025-12-31,4,Electronics,174.70,Bank Transfer
1,842,1031,2025-12-31,4,Home & Kitchen,407.37,Bank Transfer
2,261,1057,2025-12-29,4,Home & Kitchen,358.66,Bank Transfer
3,784,1190,2025-12-25,1,Books,320.24,Bank Transfer
4,998,1205,2025-12-24,2,Clothing,319.22,Bank Transfer
5,650,1066,2025-12-24,5,Sports,447.59,Bank Transfer
6,200,1060,2025-12-13,5,Clothing,156.70,Bank Transfer
7,382,1029,2025-12-13,5,Electronics,304.87,Bank Transfer
8,532,1032,2025-12-11,1,Sports,362.69,Bank Transfer
9,198,1031,2025-12-11,1,Beauty,299.46,Bank Transfer
10,14,1123,2025-12-10,4,Clothing,147.50,Bank Transfer
11,99,1199,2025-12-09,4,Home & Kitchen,491.08,Bank Transfer
12,651,1100,2025-12-06,3,Clothing,80.52,Bank Transfer
13,738,1092,2025-12-06,2,Books,217.14,Bank Transfer
14,804,1199,2025-12-06,5,Sports,136.14,Bank Transfer
15,983,1047,2025-12-05,3,Books,300.55,Bank Transfer
16,931,1004,2025-12-05,3,Clothing,466.04,Bank Transfer
17,869,1231,2025-12-04,3,Books,102.35,Bank Transfer
18,223,1207,2025-12-03,4,Clothing,27.56,Bank Transfer
19,987,1242,2025-11-30,4,Beauty,490.88,Bank Transfer
20,325,1243,2025-11-30,5,Clothing,419.76,Bank Transfer
21,513,1031,2025-11-27,5,Clothing,241.66,Bank Transfer
22,619,1159,2025-11-26,1,Home & Kitchen,142.61,Bank Transfer
23,460,1164,2025-11-22,1,Sports,269.58,Bank Transfer
24,184,1214,2025-11-22,4,Home & Kitchen,232.11,Bank Transfer
25,266,1248,2025-11-21,3,Books,14.54,Bank Transfer
26,751,1011,2025-11-18,5,Books,58.92,Bank Transfer
27,868,1081,2025-11-18,5,Electronics,78.42,Bank Transfer
28,647,1187,2025-11-17,3,Books,376.92,Bank Transfer
29,390,1150,2025-11-16,1,Sports,345.44,Bank Transfer

In [19]:
run_sql("""
    SELECT category, quantity, payment_method
    FROM orders
    WHERE quantity = 4
    ORDER BY quantity DESC
    LIMIT 30;
""")

          category  quantity    payment_method
0         Clothing         4     Bank Transfer
1   Home & Kitchen         4              Card
2      Electronics         4              Card
3      Electronics         4  Cash on Delivery
4           Beauty         4              Card
5           Sports         4  Cash on Delivery
6           Beauty         4  Cash on Delivery
7         Clothing         4              Card
8         Clothing         4              Card
9   Home & Kitchen         4     Bank Transfer
10          Beauty         4     Bank Transfer
11  Home & Kitchen         4     Bank Transfer
12           Books         4     Bank Transfer
13          Sports         4     Bank Transfer
14          Sports         4            Wallet
15          Beauty         4  Cash on Delivery
16          Sports         4            Wallet
17  Home & Kitchen         4              Card
18          Beauty         4            Wallet
19     Electronics         4              Card
20     Electronics         4     Bank Transfer
21          Sports         4     Bank Transfer
22     Electronics         4              Card
23        Clothing         4     Bank Transfer
24          Sports         4              Card
25          Beauty         4              Card
26  Home & Kitchen         4            Wallet
27           Books         4              Card
28           Books         4     Bank Transfer
29  Home & Kitchen         4  Cash on Delivery

In [20]:
# order_id	customer_id	order_date	product	category	
# quantity	unit_price	discount_percent	
# total_amount	city	payment_method	order_status

run_sql("""
    SELECT order_id, customer_id, order_date, product, discount_percent, city
    FROM orders
    WHERE city IN ('Kano', 'Port Harcourt')
    ORDER BY order_date DESC
    LIMIT 20;
""")

,order_id,customer_id,order_date,product,discount_percent,city
0,261,1057,2025-12-29,Smart Watch,10,Kano
1,285,1031,2025-12-29,Running Shoes,10,Kano
2,939,1074,2025-12-29,Yoga Mat,15,Port Harcourt
3,481,1117,2025-12-28,Python Programming Book,15,Kano
4,499,1062,2025-12-28,Coffee Maker,0,Kano
5,540,1218,2025-12-28,Smart Watch,20,Kano
6,887,1173,2025-12-28,Face Moisturizer,0,Kano
7,388,1015,2025-12-27,Python Programming Book,15,Port Harcourt
8,784,1190,2025-12-25,Python Programming Book,15,Kano
9,998,1205,2025-12-24,Coffee Maker,20,Port Harcourt
10,721,1144,2025-12-24,Face Moisturizer,15,Kano
11,649,1074,2025-12-22,Cotton T-Shirt,20,Port Harcourt
12,422,1250,2025-12-21,Coffee Maker,15,Kano
13,814,1139,2025-12-20,Cotton T-Shirt,10,Port Harcourt
14,244,1009,2025-12-17,Coffee Maker,10,Kano
15,200,1060,2025-12-13,Smart Watch,5,Port Harcourt
16,6,1239,2025-12-13,Laptop Stand,5,Port Harcourt
17,57,1212,2025-12-12,Wireless Headphones,20,Kano
18,397,1074,2025-12-11,Cotton T-Shirt,10,Kano
19,198,1031,2025-12-11,Laptop Stand,20,Kano

In [21]:
run_sql("""
    SELECT product, category, order_date, unit_price, total_amount
    FROM orders
    WHERE product = "Running Shoes" AND category = "Sports"
    ORDER BY order_date DESC
    LIMIT 20;
""")

          product category  order_date  unit_price  total_amount
0   Running Shoes   Sports  2025-12-30       91.29        173.45
1   Running Shoes   Sports  2025-11-22      269.58        256.10
2   Running Shoes   Sports  2025-10-30      116.01        522.05
3   Running Shoes   Sports  2025-09-20      115.02        517.59
4   Running Shoes   Sports  2025-09-10      330.51       1123.73
5   Running Shoes   Sports  2025-08-25       77.94        132.50
6   Running Shoes   Sports  2025-07-14      319.82        639.64
7   Running Shoes   Sports  2025-06-12      329.82        791.57
8   Running Shoes   Sports  2025-05-25      413.07       1115.29
9   Running Shoes   Sports  2025-05-21      173.71        173.71
10  Running Shoes   Sports  2025-05-09      210.89       1001.73
11  Running Shoes   Sports  2025-04-23      415.13       1660.52
12  Running Shoes   Sports  2025-04-06      457.10       2285.50
13  Running Shoes   Sports  2025-03-27      203.11        172.64
14  Running Shoes   Sports  2025-01-30      166.39        266.22