In [119]:
import sqlite3
import pandas as pd

# Create/Connect to a SQLite database file
conn = sqlite3.connect("ecommerce.db")

In [120]:
import os
print(os.getcwd())  # shows current working directory

c:\Users\ADEGOKE\Desktop\DS-ML-AI\2026-Project-Building-Class-Journey-For-Beginners

In [121]:
# Load CSV into pandas
df = pd.read_csv("data/ecommerce_dataset.csv")

In [122]:
# Save it as a SQL table
df.to_sql("orders", conn, if_exists="replace", index=False)
print(f"✅ Done! Loaded {len(df):,} rows into SQLite")
print(f"Tables in SQLite {df.columns.to_list()}")

✅ Done! Loaded 1,000 rows into SQLite
Tables in SQLite ['order_id', 'customer_id', 'order_date', 'product', 'category', 'quantity', 'unit_price', 'discount_percent', 'total_amount', 'city', 'payment_method', 'order_status']

In [123]:
# Create a Helper Function

def run_sql(query):
    return pd.read_sql(query, conn)

In [124]:
run_sql("SELECT * FROM orders;")

,order_id,customer_id,order_date,product,category,quantity,unit_price,discount_percent,total_amount,city,payment_method,order_status
0,462,1085,2025-01-01,Running Shoes,Beauty,1,222.94,20,178.35,Port Harcourt,Bank Transfer,Delivered
1,83,1193,2025-01-01,Laptop Stand,Sports,1,61.44,5,58.37,Ibadan,Card,Delivered
2,760,1174,2025-01-01,Bluetooth Speaker,Clothing,4,498.37,10,1794.13,Lagos,Bank Transfer,Delivered
3,297,1112,2025-01-02,Smart Watch,Home & Kitchen,5,19.33,5,91.82,Kano,Wallet,Cancelled
4,170,1169,2025-01-02,Yoga Mat,Beauty,1,209.89,15,178.41,Ibadan,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
995,140,1127,2025-12-30,Running Shoes,Home & Kitchen,3,434.07,10,1171.99,Lagos,Cash on Delivery,Processing
996,808,1224,2025-12-30,Bluetooth Speaker,Books,1,337.78,0,337.78,Abuja,Wallet,Processing
997,39,1077,2025-12-30,Running Shoes,Sports,2,91.29,5,173.45,Abuja,Wallet,Processing
998,602,1238,2025-12-31,Bluetooth Speaker,Electronics,4,174.70,15,593.98,Ibadan,Bank Transfer,Delivered
999,842,1031,2025-12-31,Face Moisturizer,Home & Kitchen,4,407.37,10,1466.53,Abuja,Bank Transfer,Delivered

In [125]:
run_sql("SELECT city FROM orders;")

              city
0    Port Harcourt
1           Ibadan
2            Lagos
3             Kano
4           Ibadan
..             ...
995          Lagos
996          Abuja
997          Abuja
998         Ibadan
999          Abuja

[1000 rows x 1 columns]

In [126]:
run_sql("SELECT order_id FROM orders;")

     order_id
0         462
1          83
2         760
3         297
4         170
..        ...
995       140
996       808
997        39
998       602
999       842

[1000 rows x 1 columns]

In [127]:
run_sql("SELECT payment_method FROM orders;")

       payment_method
0       Bank Transfer
1                Card
2       Bank Transfer
3              Wallet
4    Cash on Delivery
..                ...
995  Cash on Delivery
996            Wallet
997            Wallet
998     Bank Transfer
999     Bank Transfer

[1000 rows x 1 columns]

In [128]:
run_sql("SELECT * FROM orders LIMIT 5;")

,order_id,customer_id,order_date,product,category,quantity,unit_price,discount_percent,total_amount,city,payment_method,order_status
0,462,1085,2025-01-01,Running Shoes,Beauty,1,222.94,20,178.35,Port Harcourt,Bank Transfer,Delivered
1,83,1193,2025-01-01,Laptop Stand,Sports,1,61.44,5,58.37,Ibadan,Card,Delivered
2,760,1174,2025-01-01,Bluetooth Speaker,Clothing,4,498.37,10,1794.13,Lagos,Bank Transfer,Delivered
3,297,1112,2025-01-02,Smart Watch,Home & Kitchen,5,19.33,5,91.82,Kano,Wallet,Cancelled
4,170,1169,2025-01-02,Yoga Mat,Beauty,1,209.89,15,178.41,Ibadan,Cash on Delivery,Delivered

In [129]:
run_sql("PRAGMA table_info(orders);")

    cid              name     type  notnull dflt_value  pk
0     0          order_id  INTEGER        0       None   0
1     1       customer_id  INTEGER        0       None   0
2     2        order_date     TEXT        0       None   0
3     3           product     TEXT        0       None   0
4     4          category     TEXT        0       None   0
5     5          quantity  INTEGER        0       None   0
6     6        unit_price     REAL        0       None   0
7     7  discount_percent  INTEGER        0       None   0
8     8      total_amount     REAL        0       None   0
9     9              city     TEXT        0       None   0
10   10    payment_method     TEXT        0       None   0
11   11      order_status     TEXT        0       None   0

In [130]:
run_sql("""
    SELECT category, city, product, total_amount
    FROM orders
    WHERE city = 'Lagos'
    ORDER BY total_amount DESC
    LIMIT 20;
"""
)

          category   city                  product  total_amount
0           Sports  Lagos      Wireless Headphones       2398.85
1   Home & Kitchen  Lagos              Smart Watch       2377.65
2           Sports  Lagos            Running Shoes       2285.50
3            Books  Lagos            Running Shoes       2263.15
4           Beauty  Lagos        Bluetooth Speaker       2125.17
5           Beauty  Lagos  Python Programming Book       2115.56
6            Books  Lagos           Cotton T-Shirt       2070.99
7      Electronics  Lagos      Wireless Headphones       2049.82
8   Home & Kitchen  Lagos                 Yoga Mat       1964.32
9   Home & Kitchen  Lagos             Coffee Maker       1943.14
10          Sports  Lagos             Coffee Maker       1935.62
11        Clothing  Lagos  Python Programming Book       1922.18
12           Books  Lagos                 Yoga Mat       1901.61
13  Home & Kitchen  Lagos            Running Shoes       1851.35
14        Clothing  Lagos        Bluetooth Speaker       1794.13
15     Electronics  Lagos           Cotton T-Shirt       1781.49
16          Sports  Lagos      Wireless Headphones       1717.09
17          Sports  Lagos              Smart Watch       1710.20
18          Sports  Lagos           Cotton T-Shirt       1709.80
19          Sports  Lagos             Laptop Stand       1668.04

In [131]:
run_sql("""
    SELECT order_status, quantity, city, product
    FROM orders
    WHERE city = 'Ibadan'
    ORDER BY quantity DESC
    LIMIT 20;
""")

   order_status  quantity    city                  product
0     Delivered         5  Ibadan            Running Shoes
1       Shipped         5  Ibadan              Smart Watch
2     Delivered         5  Ibadan      Wireless Headphones
3     Delivered         5  Ibadan             Laptop Stand
4     Cancelled         5  Ibadan         Face Moisturizer
5     Delivered         5  Ibadan                 Yoga Mat
6     Delivered         5  Ibadan             Laptop Stand
7     Delivered         5  Ibadan  Python Programming Book
8     Delivered         5  Ibadan  Python Programming Book
9     Delivered         5  Ibadan             Laptop Stand
10    Delivered         5  Ibadan            Running Shoes
11    Delivered         5  Ibadan        Bluetooth Speaker
12      Shipped         5  Ibadan         Face Moisturizer
13      Shipped         5  Ibadan  Python Programming Book
14    Delivered         5  Ibadan           Cotton T-Shirt
15    Delivered         5  Ibadan              Smart Watch
16   Processing         5  Ibadan         Face Moisturizer
17    Delivered         5  Ibadan  Python Programming Book
18    Delivered         5  Ibadan         Face Moisturizer
19    Delivered         5  Ibadan        Bluetooth Speaker

In [132]:
run_sql("""
    SELECT order_id, customer_id, order_date, quantity, category, unit_price, payment_method 
    FROM orders
    WHERE payment_method = 'Bank Transfer'
    ORDER BY order_date DESC
    LIMIT 30
""")
# order_id	customer_id	order_date	product	category	
# quantity	unit_price	discount_percent	
# total_amount	city	payment_method	order_status

,order_id,customer_id,order_date,quantity,category,unit_price,payment_method
0,602,1238,2025-12-31,4,Electronics,174.70,Bank Transfer
1,842,1031,2025-12-31,4,Home & Kitchen,407.37,Bank Transfer
2,261,1057,2025-12-29,4,Home & Kitchen,358.66,Bank Transfer
3,784,1190,2025-12-25,1,Books,320.24,Bank Transfer
4,998,1205,2025-12-24,2,Clothing,319.22,Bank Transfer
5,650,1066,2025-12-24,5,Sports,447.59,Bank Transfer
6,200,1060,2025-12-13,5,Clothing,156.70,Bank Transfer
7,382,1029,2025-12-13,5,Electronics,304.87,Bank Transfer
8,532,1032,2025-12-11,1,Sports,362.69,Bank Transfer
9,198,1031,2025-12-11,1,Beauty,299.46,Bank Transfer
10,14,1123,2025-12-10,4,Clothing,147.50,Bank Transfer
11,99,1199,2025-12-09,4,Home & Kitchen,491.08,Bank Transfer
12,651,1100,2025-12-06,3,Clothing,80.52,Bank Transfer
13,738,1092,2025-12-06,2,Books,217.14,Bank Transfer
14,804,1199,2025-12-06,5,Sports,136.14,Bank Transfer
15,983,1047,2025-12-05,3,Books,300.55,Bank Transfer
16,931,1004,2025-12-05,3,Clothing,466.04,Bank Transfer
17,869,1231,2025-12-04,3,Books,102.35,Bank Transfer
18,223,1207,2025-12-03,4,Clothing,27.56,Bank Transfer
19,987,1242,2025-11-30,4,Beauty,490.88,Bank Transfer
20,325,1243,2025-11-30,5,Clothing,419.76,Bank Transfer
21,513,1031,2025-11-27,5,Clothing,241.66,Bank Transfer
22,619,1159,2025-11-26,1,Home & Kitchen,142.61,Bank Transfer
23,460,1164,2025-11-22,1,Sports,269.58,Bank Transfer
24,184,1214,2025-11-22,4,Home & Kitchen,232.11,Bank Transfer
25,266,1248,2025-11-21,3,Books,14.54,Bank Transfer
26,751,1011,2025-11-18,5,Books,58.92,Bank Transfer
27,868,1081,2025-11-18,5,Electronics,78.42,Bank Transfer
28,647,1187,2025-11-17,3,Books,376.92,Bank Transfer
29,390,1150,2025-11-16,1,Sports,345.44,Bank Transfer

In [133]:
run_sql("""
    SELECT category, quantity, payment_method
    FROM orders
    WHERE quantity = 4
    ORDER BY quantity DESC
    LIMIT 30;
""")

          category  quantity    payment_method
0         Clothing         4     Bank Transfer
1   Home & Kitchen         4              Card
2      Electronics         4              Card
3      Electronics         4  Cash on Delivery
4           Beauty         4              Card
5           Sports         4  Cash on Delivery
6           Beauty         4  Cash on Delivery
7         Clothing         4              Card
8         Clothing         4              Card
9   Home & Kitchen         4     Bank Transfer
10          Beauty         4     Bank Transfer
11  Home & Kitchen         4     Bank Transfer
12           Books         4     Bank Transfer
13          Sports         4     Bank Transfer
14          Sports         4            Wallet
15          Beauty         4  Cash on Delivery
16          Sports         4            Wallet
17  Home & Kitchen         4              Card
18          Beauty         4            Wallet
19     Electronics         4              Card
20     Electronics         4     Bank Transfer
21          Sports         4     Bank Transfer
22     Electronics         4              Card
23        Clothing         4     Bank Transfer
24          Sports         4              Card
25          Beauty         4              Card
26  Home & Kitchen         4            Wallet
27           Books         4              Card
28           Books         4     Bank Transfer
29  Home & Kitchen         4  Cash on Delivery

In [134]:
# order_id	customer_id	order_date	product	category	
# quantity	unit_price	discount_percent	
# total_amount	city	payment_method	order_status

run_sql("""
    SELECT order_id, customer_id, order_date, product, discount_percent, city
    FROM orders
    WHERE city IN ('Kano', 'Port Harcourt')
    ORDER BY order_date DESC
    LIMIT 20;
""")

,order_id,customer_id,order_date,product,discount_percent,city
0,261,1057,2025-12-29,Smart Watch,10,Kano
1,285,1031,2025-12-29,Running Shoes,10,Kano
2,939,1074,2025-12-29,Yoga Mat,15,Port Harcourt
3,481,1117,2025-12-28,Python Programming Book,15,Kano
4,499,1062,2025-12-28,Coffee Maker,0,Kano
5,540,1218,2025-12-28,Smart Watch,20,Kano
6,887,1173,2025-12-28,Face Moisturizer,0,Kano
7,388,1015,2025-12-27,Python Programming Book,15,Port Harcourt
8,784,1190,2025-12-25,Python Programming Book,15,Kano
9,998,1205,2025-12-24,Coffee Maker,20,Port Harcourt
10,721,1144,2025-12-24,Face Moisturizer,15,Kano
11,649,1074,2025-12-22,Cotton T-Shirt,20,Port Harcourt
12,422,1250,2025-12-21,Coffee Maker,15,Kano
13,814,1139,2025-12-20,Cotton T-Shirt,10,Port Harcourt
14,244,1009,2025-12-17,Coffee Maker,10,Kano
15,200,1060,2025-12-13,Smart Watch,5,Port Harcourt
16,6,1239,2025-12-13,Laptop Stand,5,Port Harcourt
17,57,1212,2025-12-12,Wireless Headphones,20,Kano
18,397,1074,2025-12-11,Cotton T-Shirt,10,Kano
19,198,1031,2025-12-11,Laptop Stand,20,Kano

In [135]:
run_sql("""
    SELECT product, category, order_date, unit_price, total_amount
    FROM orders
    WHERE product = "Running Shoes" AND category = "Sports"
    ORDER BY order_date DESC
    LIMIT 20;
""")

          product category  order_date  unit_price  total_amount
0   Running Shoes   Sports  2025-12-30       91.29        173.45
1   Running Shoes   Sports  2025-11-22      269.58        256.10
2   Running Shoes   Sports  2025-10-30      116.01        522.05
3   Running Shoes   Sports  2025-09-20      115.02        517.59
4   Running Shoes   Sports  2025-09-10      330.51       1123.73
5   Running Shoes   Sports  2025-08-25       77.94        132.50
6   Running Shoes   Sports  2025-07-14      319.82        639.64
7   Running Shoes   Sports  2025-06-12      329.82        791.57
8   Running Shoes   Sports  2025-05-25      413.07       1115.29
9   Running Shoes   Sports  2025-05-21      173.71        173.71
10  Running Shoes   Sports  2025-05-09      210.89       1001.73
11  Running Shoes   Sports  2025-04-23      415.13       1660.52
12  Running Shoes   Sports  2025-04-06      457.10       2285.50
13  Running Shoes   Sports  2025-03-27      203.11        172.64
14  Running Shoes   Sports  2025-01-30      166.39        266.22

In [136]:
run_sql("""
    SELECT order_id, customer_id, order_date, quantity, city, unit_price, total_amount
    FROM orders
    WHERE city IN('Lagos', 'Ibadan', 'Abuja')
    ORDER BY order_date DESC
    LIMIT 10;
""")

,order_id,customer_id,order_date,quantity,city,unit_price,total_amount
0,602,1238,2025-12-31,4,Ibadan,174.70,593.98
1,842,1031,2025-12-31,4,Abuja,407.37,1466.53
2,140,1127,2025-12-30,3,Lagos,434.07,1171.99
3,808,1224,2025-12-30,1,Abuja,337.78,337.78
4,39,1077,2025-12-30,2,Abuja,91.29,173.45
5,113,1038,2025-12-29,3,Lagos,485.21,1455.63
6,302,1165,2025-12-29,5,Abuja,165.41,785.70
7,436,1233,2025-12-28,1,Lagos,111.34,94.64
8,588,1077,2025-12-27,1,Ibadan,383.67,326.12
9,790,1149,2025-12-27,1,Abuja,288.29,273.88

In [137]:
run_sql("""
    SELECT order_id, customer_id, order_date, quantity, city, unit_price, total_amount
    FROM orders
    WHERE quantity >= 4 AND unit_price >= 400.00 AND city = 'Lagos'
    ORDER BY total_amount DESC
    LIMIT 20;
""")

,order_id,customer_id,order_date,quantity,city,unit_price,total_amount
0,885,1002,2025-02-17,5,Lagos,479.77,2398.85
1,514,1228,2025-11-14,5,Lagos,475.53,2377.65
2,947,1093,2025-04-06,5,Lagos,457.10,2285.50
3,103,1048,2025-03-30,5,Lagos,452.63,2263.15
4,914,1152,2025-02-27,5,Lagos,472.26,2125.17
5,28,1111,2025-02-05,5,Lagos,497.78,2115.56
6,265,1150,2025-11-01,5,Lagos,460.22,2070.99
7,741,1067,2025-10-01,5,Lagos,431.54,2049.82
8,99,1199,2025-12-09,4,Lagos,491.08,1964.32
9,582,1244,2025-11-02,5,Lagos,457.21,1943.14
10,195,1142,2025-05-16,5,Lagos,455.44,1935.62
11,448,1048,2025-05-30,5,Lagos,427.15,1922.18
12,12,1222,2025-01-20,5,Lagos,422.58,1901.61
13,669,1185,2025-10-04,5,Lagos,411.41,1851.35
14,760,1174,2025-01-01,4,Lagos,498.37,1794.13
15,416,1111,2025-03-25,4,Lagos,476.97,1717.09
16,820,1233,2025-07-27,5,Lagos,427.55,1710.20
17,428,1121,2025-02-20,5,Lagos,427.45,1709.80
18,615,1141,2025-07-28,4,Lagos,490.60,1668.04
19,105,1020,2025-02-09,4,Lagos,481.97,1638.70

In [138]:
run_sql("""
    SELECT order_id, customer_id, order_date, quantity, city, unit_price, total_amount
    FROM orders
    WHERE quantity >= 4 OR unit_price >= 400.00 OR city = 'Lagos'
    ORDER BY total_amount DESC
    LIMIT 20;
""")

,order_id,customer_id,order_date,quantity,city,unit_price,total_amount
0,499,1062,2025-12-28,5,Kano,496.75,2483.75
1,835,1245,2025-04-04,5,Port Harcourt,482.15,2410.75
2,885,1002,2025-02-17,5,Lagos,479.77,2398.85
3,514,1228,2025-11-14,5,Lagos,475.53,2377.65
4,527,1005,2025-08-03,5,Ibadan,474.29,2371.45
5,959,1230,2025-08-12,5,Ibadan,473.39,2366.95
6,694,1216,2025-03-26,5,Kano,488.04,2318.19
7,947,1093,2025-04-06,5,Lagos,457.10,2285.50
8,103,1048,2025-03-30,5,Lagos,452.63,2263.15
9,125,1198,2025-02-12,5,Kano,489.18,2201.31
10,693,1248,2025-11-20,5,Port Harcourt,438.79,2193.95
11,220,1041,2025-05-09,5,Ibadan,478.12,2151.54
12,914,1152,2025-02-27,5,Lagos,472.26,2125.17
13,609,1219,2025-08-10,5,Kano,499.32,2122.11
14,28,1111,2025-02-05,5,Lagos,497.78,2115.56
15,852,1182,2025-08-04,5,Abuja,420.48,2102.40
16,812,1062,2025-08-25,5,Ibadan,462.71,2082.19
17,265,1150,2025-11-01,5,Lagos,460.22,2070.99
18,686,1182,2025-06-09,5,Ibadan,413.32,2066.60
19,741,1067,2025-10-01,5,Lagos,431.54,2049.82

### IS NULL - IS NOT NULL TO CHECK FOR MISSING VALUES

- **`IS NULL` / `IS NOT NULL`**: Used to check for missing or populated values (presence/absence of data).

In [139]:
run_sql("""
    SELECT order_date, order_id, city, quantity, unit_price
    FROM orders
    WHERE unit_price IS NULL;
""")

Empty DataFrame
Columns: [order_date, order_id, city, quantity, unit_price]
Index: []

In [140]:
run_sql("""
    SELECT order_date, order_id, city, quantity, unit_price
    FROM orders
    WHERE unit_price IS NOT NULL
    LIMIT 20;
""")

    order_date  order_id           city  quantity  unit_price
0   2025-01-01       462  Port Harcourt         1      222.94
1   2025-01-01        83         Ibadan         1       61.44
2   2025-01-01       760          Lagos         4      498.37
3   2025-01-02       297           Kano         5       19.33
4   2025-01-02       170         Ibadan         1      209.89
5   2025-01-03       719           Kano         2      341.56
6   2025-01-03       844          Lagos         1      286.55
7   2025-01-04       603          Abuja         4      400.78
8   2025-01-05       438  Port Harcourt         5       69.12
9   2025-01-05       916         Ibadan         3      399.94
10  2025-01-05       880          Abuja         4      220.22
11  2025-01-05        78          Abuja         2      297.69
12  2025-01-06       142          Abuja         2      402.43
13  2025-01-07        68         Ibadan         2       38.47
14  2025-01-07       745         Ibadan         4      185.11
15  2025-01-08       621          Lagos         3      335.09
16  2025-01-08       897          Abuja         3      272.10
17  2025-01-08        35  Port Harcourt         5       15.26
18  2025-01-08       411  Port Harcourt         1      384.75
19  2025-01-08       746         Ibadan         2      139.76

### LIKE
- **`LIKE`**: Used for **text pattern matching** using wildcards (like `%` for multiple characters and `_` for a single character) to find specific words or letters.

In [141]:
# Find all orders placed by customers whose city starts with the letter 'L', and order by customer_id descending
run_sql("""
    SELECT customer_id, city
    FROM orders
    WHERE city LIKE 'L%'
    ORDER BY customer_id DESC
    LIMIT 10;
""")

   customer_id   city
0         1250  Lagos
1         1246  Lagos
2         1244  Lagos
3         1244  Lagos
4         1242  Lagos
5         1238  Lagos
6         1234  Lagos
7         1233  Lagos
8         1233  Lagos
9         1233  Lagos

In [142]:
# Retrieve all records where the order_status or description contains the text 'cell' anywhere inside it.
run_sql("""
    SELECT  order_date, product, order_status
    FROM orders
    WHERE order_status LIKE '%cell%'
    ORDER BY order_date
    LIMIT 20;
""")

    order_date                  product order_status
0   2025-01-02              Smart Watch    Cancelled
1   2025-01-10         Face Moisturizer    Cancelled
2   2025-01-23  Python Programming Book    Cancelled
3   2025-02-13           Cotton T-Shirt    Cancelled
4   2025-02-22        Bluetooth Speaker    Cancelled
5   2025-02-23              Smart Watch    Cancelled
6   2025-02-26  Python Programming Book    Cancelled
7   2025-02-26            Running Shoes    Cancelled
8   2025-03-03             Coffee Maker    Cancelled
9   2025-03-04              Smart Watch    Cancelled
10  2025-03-09           Cotton T-Shirt    Cancelled
11  2025-03-12         Face Moisturizer    Cancelled
12  2025-03-13  Python Programming Book    Cancelled
13  2025-03-23              Smart Watch    Cancelled
14  2025-04-02              Smart Watch    Cancelled
15  2025-04-02      Wireless Headphones    Cancelled
16  2025-04-14        Bluetooth Speaker    Cancelled
17  2025-05-15            Running Shoes    Cancelled
18  2025-05-20             Laptop Stand    Cancelled
19  2025-05-24         Face Moisturizer    Cancelled

In [143]:
# Retrieve all records where the product or description contains the text 'Head' anywhere inside it.
run_sql("""
    SELECT order_date, customer_id, product
    FROM orders
    WHERE product LIKE '%Head%'
    ORDER BY order_date DESC
    LIMIT 20;
""")

    order_date  customer_id              product
0   2025-12-29         1165  Wireless Headphones
1   2025-12-28         1233  Wireless Headphones
2   2025-12-22         1065  Wireless Headphones
3   2025-12-12         1212  Wireless Headphones
4   2025-12-08         1050  Wireless Headphones
5   2025-12-06         1177  Wireless Headphones
6   2025-12-06         1087  Wireless Headphones
7   2025-12-05         1004  Wireless Headphones
8   2025-12-03         1232  Wireless Headphones
9   2025-11-30         1086  Wireless Headphones
10  2025-11-30         1198  Wireless Headphones
11  2025-11-27         1031  Wireless Headphones
12  2025-11-25         1229  Wireless Headphones
13  2025-11-23         1224  Wireless Headphones
14  2025-11-22         1180  Wireless Headphones
15  2025-11-21         1248  Wireless Headphones
16  2025-11-18         1242  Wireless Headphones
17  2025-11-13         1126  Wireless Headphones
18  2025-11-11         1202  Wireless Headphones
19  2025-10-27         1101  Wireless Headphones

In [144]:
# Find all orders where the city ends with 'dan' and oder got cancelled.
run_sql("""
    SELECT customer_id, product, city, order_status
    FROM orders
    WHERE city LIKE '%dan%' AND order_status = 'Cancelled';
""")

   customer_id                  product    city order_status
0         1092           Cotton T-Shirt  Ibadan    Cancelled
1         1040              Smart Watch  Ibadan    Cancelled
2         1213         Face Moisturizer  Ibadan    Cancelled
3         1150        Bluetooth Speaker  Ibadan    Cancelled
4         1185         Face Moisturizer  Ibadan    Cancelled
5         1105  Python Programming Book  Ibadan    Cancelled
6         1021      Wireless Headphones  Ibadan    Cancelled
7         1199             Coffee Maker  Ibadan    Cancelled
8         1248  Python Programming Book  Ibadan    Cancelled

In [145]:
# Select all rows where a text column contains a specific keyword (e.g., 'as' in a payment method or city name).
run_sql("""
    SELECT *
    FROM orders
    WHERE payment_method LIMIT '%as%' AND city LIMIT '%no'
""")

DatabaseError: Execution failed on sql '
    SELECT *
    FROM orders
    WHERE payment_method LIMIT '%as%' AND city LIMIT '%no'
': near "LIMIT": syntax error

In [ ]:
# Find all records where a city name has exactly 5 letters (e.g., 'Abuja' or 'Kano ').
run_sql("""
    SELECT *
    FROM orders
    WHERE city LIMIT '_____';
""")

DatabaseError: Execution failed on sql '
    SELECT *
    FROM orders
    WHERE city LIMIT '_____';
': datatype mismatch

In [ ]:
# Find a product code or ID where the third character is always a specific letter or number (e.g., __X% or similar pattern).
run_sql("""
    SELECT customer_id, product
    FROM orders
    WHERE customer_id LIMIT '___3%' OR product LIMIT '___s%',
""")

DatabaseError: Execution failed on sql '
    SELECT customer_id, product
    FROM orders
    WHERE customer_id LIMIT '___3%' OR product LIMIT '___s%'
': near "LIMIT": syntax error

In [147]:
# Find customers whose city are exactly 4 letters long.
run_sql("""
    SELECT city
    FROM orders
    WHERE city LIMIT '___o';
""")

DatabaseError: Execution failed on sql '
    SELECT city
    FROM orders
    WHERE city LIMIT '___o';
': datatype mismatch

In [148]:
# Retrieve orders where a specific 3-letter code appears at the beginning, followed by any characters.
run_sql("""
    SELECT order_id, product
    FROM orders
    WHERE product LIMIT 'Run____';
""")

DatabaseError: Execution failed on sql '
    SELECT order_id, product
    FROM orders
    WHERE product LIMIT 'Run____';
': datatype mismatch